language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

script:
 - ./gradlew build
 - ./gradlew test